#!/bin/bash

BASE=$(readlink -f "$0" | xargs dirname)

for path in $(cat /etc/pve/storage.cfg | grep path | awk '{print $2}' | sort | uniq); do
	find $path -name "*.qcow2" -type f -exec $BASE/qcow2-check "{}" \;
done
